services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all